[tool.cibuildwheel]

before-all = [
  "yum install -y openmpi-devel",
]

environment = { PATH=/usr/lib64/openmpi/bin:${PATH},
                LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:${LD_LIBRARY_PATH},
                MPI_INCLUDE=/usr/include/openmpi-x86_64,
                MPI_LIB=/usr/lib64/openmpi/lib,
                MPI_BIN=/usr/lib64/openmpi/bin,
                MPI_COMPILER=openmpi-x86_64,
                MPI_SYSCONFIG=/etc/openmpi-x86_64,
                MPI_SUFFIX=_openmpi,
                MPI_HOME=/usr/lib64/openmpi,
                MPI_FORTRAN_MOD_DIR=/usr/lib64/gfortran/modules/openmpi-x86_64
}
