name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

#- name: Set up Gfortran
#  if: runner.os == 'macOS'
#  run: ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dependencies
          channels: conda-forge,defaults
          environment-file: conda_env.yml


      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
